const locationsTypeSelect = [
  // Countries
  { value: 'argentina', label: 'Argentina' },
  { value: 'australia', label: 'Australia' },
  { value: 'austria', label: 'Austria' },
  { value: 'belgium', label: 'Belgium' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'bulgaria', label: 'Bulgaria' },
  { value: 'canada', label: 'Canada' },
  { value: 'chile', label: 'Chile' },
  { value: 'china', label: 'China' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'costa-rica', label: 'Costa Rica' },
  { value: 'croatia', label: 'Croatia' },
  { value: 'czech-republic', label: 'Czech Republic' },
  { value: 'denmark', label: 'Denmark' },
  { value: 'dominican-republic', label: 'Dominican Republic' },
  { value: 'egypt', label: 'Egypt' },
  { value: 'finland', label: 'Finland' },
  { value: 'france', label: 'France' },
  { value: 'germany', label: 'Germany' },
  { value: 'greece', label: 'Greece' },
  { value: 'hungary', label: 'Hungary' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'ireland', label: 'Ireland' },
  { value: 'israel', label: 'Israel' },
  { value: 'italy', label: 'Italy' },
  { value: 'japan', label: 'Japan' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'mexico', label: 'Mexico' },
  { value: 'netherlands', label: 'Netherlands' },
  { value: 'new-zealand', label: 'New Zealand' },
  { value: 'norway', label: 'Norway' },
  { value: 'philippines', label: 'Philippines' },
  { value: 'poland', label: 'Poland' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'qatar', label: 'Qatar' },
  { value: 'romania', label: 'Romania' },
  { value: 'russia', label: 'Russia' },
  { value: 'saudi-arabia', label: 'Saudi Arabia' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'south-africa', label: 'South Africa' },
  { value: 'south-korea', label: 'South Korea' },
  { value: 'spain', label: 'Spain' },
  { value: 'sweden', label: 'Sweden' },
  { value: 'switzerland', label: 'Switzerland' },
  { value: 'thailand', label: 'Thailand' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'united-arab-emirates', label: 'United Arab Emirates (UAE)' },
  { value: 'united-kingdom', label: 'United Kingdom (UK)' },
  { value: 'united-states', label: 'United States of America (USA)' },

  // Cities
  { value: 'abu-dhabi', label: 'Abu Dhabi, UAE' },
  { value: 'ankara', label: 'Ankara, Turkey' },
  { value: 'antalya', label: 'Antalya, Turkey' },
  { value: 'athens', label: 'Athens, Greece' },
  { value: 'atlanta', label: 'Atlanta, USA' },
  { value: 'bangkok', label: 'Bangkok, Thailand' },
  { value: 'barcelona', label: 'Barcelona, Spain' },
  { value: 'beijing', label: 'Beijing, China' },
  { value: 'beirut', label: 'Beirut, Lebanon' },
  { value: 'berlin', label: 'Berlin, Germany' },
  { value: 'beverly-hills', label: 'Beverly Hills, USA' },
  { value: 'bogota', label: 'Bogota, Colombia' },
  { value: 'boston', label: 'Boston, USA' },
  { value: 'brasilia', label: 'Brasilia, Brazil' },
  { value: 'brussels', label: 'Brussels, Belgium' },
  { value: 'budapest', label: 'Budapest, Hungary' },
  { value: 'buenos-aires', label: 'Buenos Aires, Argentina' },
  { value: 'busan', label: 'Busan, South Korea' },
  { value: 'cairo', label: 'Cairo, Egypt' },
  { value: 'calgary', label: 'Calgary, Canada' },
  { value: 'cancun', label: 'Cancun, Mexico' },
  { value: 'cape-town', label: 'Cape Town, South Africa' },
  { value: 'chennai', label: 'Chennai, India' },
  { value: 'chicago', label: 'Chicago, USA' },
  { value: 'colombo', label: 'Colombo, Sri Lanka' },
  { value: 'copenhagen', label: 'Copenhagen, Denmark' },
  { value: 'dallas', label: 'Dallas, USA' },
  { value: 'dubai', label: 'Dubai, UAE' },
  { value: 'dublin', label: 'Dublin, Ireland' },
  { value: 'florence', label: 'Florence, Italy' },
  { value: 'frankfurt', label: 'Frankfurt, Germany' },
  { value: 'geneva', label: 'Geneva, Switzerland' },
  { value: 'glasgow', label: 'Glasgow, UK' },
  { value: 'guadalajara', label: 'Guadalajara, Mexico' },
  { value: 'hamburg', label: 'Hamburg, Germany' },
  { value: 'hanoi', label: 'Hanoi, Vietnam' },
  { value: 'ho-chi-minh-city', label: 'Ho Chi Minh City, Vietnam' },
  { value: 'hong-kong', label: 'Hong Kong, China' },
  { value: 'honolulu', label: 'Honolulu, USA' },
  { value: 'houston', label: 'Houston, USA' },
  { value: 'istanbul', label: 'Istanbul, Turkey' },
  { value: 'jakarta', label: 'Jakarta, Indonesia' },
  { value: 'johannesburg', label: 'Johannesburg, South Africa' },
  { value: 'kuala-lumpur', label: 'Kuala Lumpur, Malaysia' },
  { value: 'kuwait-city', label: 'Kuwait City, Kuwait' },
  { value: 'las-vegas', label: 'Las Vegas, USA' },
  { value: 'lima', label: 'Lima, Peru' },
  { value: 'lisbon', label: 'Lisbon, Portugal' },
  { value: 'london', label: 'London, UK' },
  { value: 'los-angeles', label: 'Los Angeles, USA' },
  { value: 'lyon', label: 'Lyon, France' },
  { value: 'madrid', label: 'Madrid, Spain' },
  { value: 'manila', label: 'Manila, Philippines' },
  { value: 'marrakesh', label: 'Marrakesh, Morocco' },
  { value: 'marseille', label: 'Marseille, France' },
  { value: 'medellin', label: 'Medellin, Colombia' },
  { value: 'melbourne', label: 'Melbourne, Australia' },
  { value: 'mexico-city', label: 'Mexico City, Mexico' },
  { value: 'miami', label: 'Miami, USA' },
  { value: 'milan', label: 'Milan, Italy' },
  { value: 'montreal', label: 'Montreal, Canada' },
  { value: 'moscow', label: 'Moscow, Russia' },
  { value: 'mumbai', label: 'Mumbai, India' },
  { value: 'munich', label: 'Munich, Germany' },
  { value: 'nairobi', label: 'Nairobi, Kenya' },
  { value: 'naples', label: 'Naples, Italy' },
  { value: 'new-delhi', label: 'New Delhi, India' },
  { value: 'new-york-city', label: 'New York City, USA' },
  { value: 'nice', label: 'Nice, France' },
  { value: 'osaka', label: 'Osaka, Japan' },
  { value: 'ottawa', label: 'Ottawa, Canada' },
  { value: 'paris', label: 'Paris, France' },
  { value: 'perth', label: 'Perth, Australia' },
  { value: 'phuket', label: 'Phuket, Thailand' },
  { value: 'prague', label: 'Prague, Czech Republic' },
  { value: 'puerto-vallarta', label: 'Puerto Vallarta, Mexico' },
  { value: 'punta-cana', label: 'Punta Cana, Dominican Republic' },
  { value: 'quebec-city', label: 'Quebec City, Canada' },
  { value: 'rio-de-janeiro', label: 'Rio de Janeiro, Brazil' },
  { value: 'riyadh', label: 'Riyadh, Saudi Arabia' },
  { value: 'rome', label: 'Rome, Italy' },
  { value: 'santiago', label: 'Santiago, Chile' },
  { value: 'sao-paulo', label: 'Sao Paulo, Brazil' },
  { value: 'seattle', label: 'Seattle, USA' },
  { value: 'seoul', label: 'Seoul, South Korea' },
  { value: 'shanghai', label: 'Shanghai, China' },
  { value: 'singapore-city', label: 'Singapore, Singapore' },
  { value: 'stockholm', label: 'Stockholm, Sweden' },
  { value: 'sydney', label: 'Sydney, Australia' },
  { value: 'taipei', label: 'Taipei, Taiwan' },
  { value: 'tel-aviv', label: 'Tel Aviv, Israel' },
  { value: 'tokyo', label: 'Tokyo, Japan' },
  { value: 'toronto', label: 'Toronto, Canada' },
  { value: 'turin', label: 'Turin, Italy' },
  { value: 'vancouver', label: 'Vancouver, Canada' },
  { value: 'venice', label: 'Venice, Italy' },
  { value: 'vienna', label: 'Vienna, Austria' },
  { value: 'warsaw', label: 'Warsaw, Poland' },
  { value: 'washington-dc', label: 'Washington DC, USA' },
  { value: 'zurich', label: 'Zurich, Switzerland' },
  { value: 'adelaide', label: 'Adelaide, Australia' },
  { value: 'addis-ababa', label: 'Addis Ababa, Ethiopia' },
  { value: 'ahmedabad', label: 'Ahmedabad, India' },
  { value: 'albuquerque', label: 'Albuquerque, USA' },
  { value: 'alexandria', label: 'Alexandria, Egypt' },
  { value: 'amman', label: 'Amman, Jordan' },
  { value: 'amsterdam', label: 'Amsterdam, Netherlands' },
  { value: 'anchorage', label: 'Anchorage, USA' },
  { value: 'antwerp', label: 'Antwerp, Belgium' },
  { value: 'auckland', label: 'Auckland, New Zealand' },
  { value: 'austin', label: 'Austin, USA' },
  { value: 'baghdad', label: 'Baghdad, Iraq' },
  { value: 'bangalore', label: 'Bangalore, India' },
  { value: 'baltimore', label: 'Baltimore, USA' },
  { value: 'basel', label: 'Basel, Switzerland' },
  { value: 'belo-horizonte', label: 'Belo Horizonte, Brazil' },
  { value: 'belgrade', label: 'Belgrade, Serbia' },
  { value: 'birmingham', label: 'Birmingham, UK' },
  { value: 'bologna', label: 'Bologna, Italy' },
  { value: 'bordeaux', label: 'Bordeaux, France' },
  { value: 'bratislava', label: 'Bratislava, Slovakia' },
  { value: 'brisbane', label: 'Brisbane, Australia' },
  { value: 'bristol', label: 'Bristol, UK' },
  { value: 'bucharest', label: 'Bucharest, Romania' },
  { value: 'casablanca', label: 'Casablanca, Morocco' },
  { value: 'chandigarh', label: 'Chandigarh, India' },
  { value: 'chiang-mai', label: 'Chiang Mai, Thailand' },
  { value: 'charlotte', label: 'Charlotte, USA' },
  { value: 'chengdu', label: 'Chengdu, China' },
  { value: 'chongqing', label: 'Chongqing, China' },
  { value: 'cleveland', label: 'Cleveland, USA' },
  { value: 'cologne', label: 'Cologne, Germany' },
  { value: 'dalian', label: 'Dalian, China' },
  { value: 'dammam', label: 'Dammam, Saudi Arabia' },
  { value: 'detroit', label: 'Detroit, USA' },
  { value: 'dhaka', label: 'Dhaka, Bangladesh' },
  { value: 'doha', label: 'Doha, Qatar' },
  { value: 'dresden', label: 'Dresden, Germany' },
  { value: 'durban', label: 'Durban, South Africa' },
  { value: 'dusseldorf', label: 'Düsseldorf, Germany' },
  { value: 'edinburgh', label: 'Edinburgh, UK' },
  { value: 'eindhoven', label: 'Eindhoven, Netherlands' },
  { value: 'fukuoka', label: 'Fukuoka, Japan' },
  { value: 'gothenburg', label: 'Gothenburg, Sweden' },
  { value: 'guangzhou', label: 'Guangzhou, China' },
  { value: 'the-hague', label: 'The Hague, Netherlands' },
  { value: 'halifax', label: 'Halifax, Canada' },
  { value: 'helsinki', label: 'Helsinki, Finland' },
  { value: 'hiroshima', label: 'Hiroshima, Japan' },
  { value: 'hyderabad', label: 'Hyderabad, India' },
  { value: 'innsbruck', label: 'Innsbruck, Austria' },
  { value: 'izmir', label: 'Izmir, Turkey' },
  { value: 'jeddah', label: 'Jeddah, Saudi Arabia' },
  { value: 'karachi', label: 'Karachi, Pakistan' },
  { value: 'kathmandu', label: 'Kathmandu, Nepal' },
  { value: 'kolkata', label: 'Kolkata, India' },
  { value: 'krakow', label: 'Krakow, Poland' },
  { value: 'leeds', label: 'Leeds, UK' },
  { value: 'leipzig', label: 'Leipzig, Germany' },
  { value: 'lille', label: 'Lille, France' },
  { value: 'liverpool', label: 'Liverpool, UK' },
  { value: 'ljubljana', label: 'Ljubljana, Slovenia' },
  { value: 'louisville', label: 'Louisville, USA' },
  { value: 'lucknow', label: 'Lucknow, India' },
  { value: 'luxembourg-city', label: 'Luxembourg City, Luxembourg' },
  { value: 'macau', label: 'Macau, China' },
  { value: 'malaga', label: 'Malaga, Spain' },
  { value: 'manama', label: 'Manama, Bahrain' },
  { value: 'maputo', label: 'Maputo, Mozambique' },
  { value: 'mashhad', label: 'Mashhad, Iran' },
  { value: 'memphis', label: 'Memphis, USA' },
  { value: 'merida', label: 'Merida, Mexico' },
  { value: 'monterrey', label: 'Monterrey, Mexico' },
  { value: 'nagoya', label: 'Nagoya, Japan' },
  { value: 'nicosia', label: 'Nicosia, Cyprus' },
  { value: 'ningbo', label: 'Ningbo, China' },
  { value: 'nuremberg', label: 'Nuremberg, Germany' },
  { value: 'orlando', label: 'Orlando, USA' },
  { value: 'oslo', label: 'Oslo, Norway' },
  { value: 'panama-city', label: 'Panama City, Panama' },
  { value: 'penang', label: 'Penang, Malaysia' },
  { value: 'philadelphia', label: 'Philadelphia, USA' },
  { value: 'pittsburgh', label: 'Pittsburgh, USA' },
  { value: 'pune', label: 'Pune, India' },
  { value: 'raleigh', label: 'Raleigh, USA' },
  { value: 'recife', label: 'Recife, Brazil' },
  { value: 'reykjavik', label: 'Reykjavik, Iceland' },
  { value: 'rotterdam', label: 'Rotterdam, Netherlands' },
  { value: 'san-antonio', label: 'San Antonio, USA' },
  { value: 'san-francisco', label: 'San Francisco, USA' },
  { value: 'santo-domingo', label: 'Santo Domingo, Dominican Republic' },
  { value: 'sharjah', label: 'Sharjah, UAE' },
  { value: 'sheffield', label: 'Sheffield, UK' },
  { value: 'shenzhen', label: 'Shenzhen, China' },
  { value: 'sofia', label: 'Sofia, Bulgaria' },
  { value: 'split', label: 'Split, Croatia' },
  { value: 'stavanger', label: 'Stavanger, Norway' },
  { value: 'strasbourg', label: 'Strasbourg, France' },
  { value: 'stuttgart', label: 'Stuttgart, Germany' },
  { value: 'tbilisi', label: 'Tbilisi, Georgia' },
];

export default locationsTypeSelect;
